In [11]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

enade = []

#ENADE 2017
enade2017 = pandas.read_csv("datasets\MICRODADOS_ENADE_2017.txt", sep=';',dtype={"DS_VT_ESC_OFG": str, 
                                                                               'DS_VT_ESC_OCE':str,
                                                                              'DS_VT_ACE_OCE':str,
                                                                              'NT_GER':str,
                                                                              'NT_FG':str,
                                                                              'NT_OBJ_FG':str,
                                                                              'NT_DIS_FG':str,
                                                                              'NT_CE':str,
                                                                              'NT_OBJ_CE':str,
                                                                              'NT_DIS_CE':str,
                                                                            'CO_CATEGAD':str})


enade2017.shape
enade2017.columns[0:14]
enade.append(enade2017)

In [12]:
#ENADE 2016
enade2016 = pandas.read_csv("datasets\MICRODADOS_ENADE_2016.txt", sep=';',dtype={"DS_VT_ESC_OFG": str, 
                                                                               'DS_VT_ESC_OCE':str,
                                                                              'DS_VT_ACE_OCE':str,
                                                                              'NT_GER':str,
                                                                              'NT_FG':str,
                                                                              'NT_OBJ_FG':str,
                                                                              'NT_DIS_FG':str,
                                                                              'NT_CE':str,
                                                                              'NT_OBJ_CE':str,
                                                                              'NT_DIS_CE':str,
                                                                            'CO_CATEGAD':str})


enade2016.shape
enade2016.columns[0:14]
enade.append(enade2016)

In [13]:
#ENADE 2015
enade2015 = pandas.read_csv("datasets\MICRODADOS_ENADE_2015.txt", sep=';',dtype={"DS_VT_ESC_OFG": str, 
                                                                               'DS_VT_ESC_OCE':str,
                                                                              'DS_VT_ACE_OCE':str,
                                                                              'NT_GER':str,
                                                                              'NT_FG':str,
                                                                              'NT_OBJ_FG':str,
                                                                              'NT_DIS_FG':str,
                                                                              'NT_CE':str,
                                                                              'NT_OBJ_CE':str,
                                                                              'NT_DIS_CE':str,
                                                                            'CO_CATEGAD':str,
                                                                            'NU_IDADE':str,
                                                                            'CO_REGIAO_CURSO':str}, low_memory=False)


enade2015.shape
enade2015.columns[0:14]
enade.append(enade2015)

In [14]:
#ENADE 2014
enade2014 = pandas.read_csv("datasets\MICRODADOS_ENADE_2014.txt", sep=';',dtype={"DS_VT_ESC_OFG": str, 
                                                                               'DS_VT_ESC_OCE':str,
                                                                              'DS_VT_ACE_OCE':str,
                                                                              'NT_GER':str,
                                                                              'NT_FG':str,
                                                                              'NT_OBJ_FG':str,
                                                                              'NT_DIS_FG':str,
                                                                              'NT_CE':str,
                                                                              'NT_OBJ_CE':str,
                                                                              'NT_DIS_CE':str,
                                                                            'CO_CATEGAD':str,
                                                                            'NU_IDADE':str,
                                                                            'CO_REGIAO_CURSO':str}, low_memory=False)



enade2014.shape
enade2014.columns[0:14]
enade.append(enade2014)

In [15]:
#ENADE 2013
enade2013 = pandas.read_csv("datasets\MICRODADOS_ENADE_2013.txt", sep=';',dtype={"DS_VT_ESC_OFG": str, 
                                                                               'DS_VT_ESC_OCE':str,
                                                                              'DS_VT_ACE_OCE':str,
                                                                              'NT_GER':str,
                                                                              'NT_FG':str,
                                                                              'NT_OBJ_FG':str,
                                                                              'NT_DIS_FG':str,
                                                                              'NT_CE':str,
                                                                              'NT_OBJ_CE':str,
                                                                              'NT_DIS_CE':str,
                                                                            'CO_CATEGAD':str,
                                                                            'NU_IDADE':str,
                                                                            'CO_REGIAO_CURSO':str}, low_memory=False)


enade2013.shape
enade2013.columns[0:14]
enade.append(enade2013)

In [16]:
tabela = []

#TODAS
tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/cor
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'NU_IDADE', 'TP_SEXO', 'QE_I08'])

#s/RENDA
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I02'])

#s/SEXO
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'QE_I08', 'QE_I02'])

#s/IDADE
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/Q17
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/regiao
# tabela17 = pandas.DataFrame(enade[0], columns = ['CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

##Ignora valores nulos
tabela17 = tabela17.loc[(tabela17['CO_REGIAO_CURSO'].notnull())]
tabela17 = tabela17.loc[(tabela17['CO_CATEGAD'].notnull())]
tabela17 = tabela17.loc[(tabela17['QE_I17'].notnull())]
tabela17 = tabela17.loc[(tabela17['NU_IDADE'].notnull())]
tabela17 = tabela17.loc[(tabela17['QE_I02'].notnull())]
tabela17 = tabela17.loc[(tabela17['TP_SEXO'].notnull())]
tabela17 = tabela17.loc[(tabela17['QE_I08'].notnull())]
# tabela17 = tabela17.loc[(tabela17['CO_TURNO_GRADUACAO'].notnull())]


'''
1 - A = Todo em escola pública, D = A maior parte em escola pública.
2 - B = Todo em escola privada (particular), E = A maior parte em escola privada (particular).
3 - C = Todo no exterior, F = Parte no Brasil e parte no exterior
'''

##Mapeamento questão 17
tabela17['QE_I17'] = tabela17['QE_I17'].map({'A': 1, 'B': 2, 'C': 3, 'D': 1,'E': 2, 'F':3})

#Mapeamento tipo sexo
tabela17['TP_SEXO'] = tabela17['TP_SEXO'].map({'M': 0, 'F': 1})
#tabela.head(10)

##Mapeamento CO_CATEGAD
tabela17['CO_CATEGAD'] = tabela17['CO_CATEGAD'].map({'1': 0, '2': 0, '3': 0, '4' : 1, '5' : 1, '7' : 2})

# ##Mapeamento RENDA
tabela17['QE_I08'] = tabela17['QE_I08'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6, 'G' : 7})

# ##Mapeamento COR
tabela17['QE_I02'] = tabela17['QE_I02'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6})

tabela.append(tabela17)

In [17]:
#TODAS
tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/cor
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'NU_IDADE', 'TP_SEXO', 'QE_I08'])

#s/RENDA
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I02'])

#s/SEXO
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'QE_I08', 'QE_I02'])

#s/IDADE
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/Q17
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/regiao
# tabela16 = pandas.DataFrame(enade[1], columns = ['CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

##Ignora valores nulos
tabela16 = tabela16.loc[(tabela16['CO_REGIAO_CURSO'].notnull())]
tabela16 = tabela16.loc[(tabela16['CO_CATEGAD'].notnull())]
tabela16 = tabela16.loc[(tabela16['QE_I17'].notnull())]
tabela16 = tabela16.loc[(tabela16['NU_IDADE'].notnull())]
tabela16 = tabela16.loc[(tabela16['QE_I02'].notnull())]
tabela16 = tabela16.loc[(tabela16['TP_SEXO'].notnull())]
tabela16 = tabela16.loc[(tabela16['QE_I08'].notnull())]
# tabela16 = tabela16.loc[(tabela16['CO_TURNO_GRADUACAO'].notnull())]

'''
1 - A = Todo em escola pública, D = A maior parte em escola pública.
2 - B = Todo em escola privada (particular), E = A maior parte em escola privada (particular).
3 - C = Todo no exterior, F = Parte no Brasil e parte no exterior
'''

''' Código da categoria administrativa da IES
93 = Pessoa Jurídica de Direito Público - Federal 
115 = Pessoa Jurídica de Direito Público - Estadual
116 = Pessoa Jurídica de Direito Público - Municipal
118 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Civil
121 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Fundação
10001 = Pessoa Jurídica de Direito Público - Estadual
10002 = Pessoa Jurídica de Direito Público - Federal
10003 = Pessoa Jurídica de Direito Público - Municipal
10004 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Associação de Utilidade Pública
10005 = Privada com fins lucrativos
10006 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Mercantil ou Comercial
10007 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Associação de Utilidade Pública
10008 = Privada sem fins lucrativos
10009 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Sociedade
'''

##Mapeamento CO_CATEGAD
# 0 = publica, 1 = privada
tabela16['CO_CATEGAD'] = tabela16['CO_CATEGAD'].map({'93': 0, '115': 0, '116': 0, '118' : 1, '121' : 1, '10002': 0,
                                                     '10001' : 0, '10003' : 0, '10004' : 1, '10005' : 1, '10006' : 1, 
                                                    '10007' : 1, '10008' : 1, '10009' : 1})

#Mapeamento tipo sexo
tabela16['TP_SEXO'] = tabela16['TP_SEXO'].map({'M': 0, 'F': 1, 'N' : 3})
#tabela.head(10)

# ##Mapeamento RENDA
tabela16['QE_I08'] = tabela16['QE_I08'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6, 'G' : 7})

# ##Mapeamento COR
tabela16['QE_I02'] = tabela16['QE_I02'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6})

##Mapeamento questão 17
tabela16['QE_I17'] = tabela16['QE_I17'].map({'A': 1, 'B': 2, 'C': 3, 'D': 1,'E': 2, 'F':3})

#tabela.head(10)

tabela.append(tabela16)
#tabela[1].head(10)

In [18]:
#TODAS
tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/cor
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'NU_IDADE', 'TP_SEXO', 'QE_I08'])

#s/RENDA
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I02'])

#s/SEXO
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'QE_I08', 'QE_I02'])

#s/IDADE
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/Q17
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/regiao
# tabela15 = pandas.DataFrame(enade[2], columns = ['CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

##Ignora valores nulos
tabela15 = tabela15.loc[(tabela15['CO_REGIAO_CURSO'].notnull())]
tabela15 = tabela15.loc[(tabela15['CO_CATEGAD'].notnull())]
tabela15 = tabela15.loc[(tabela15['QE_I17'].notnull())]
tabela15 = tabela15.loc[(tabela15['NU_IDADE'].notnull())]
tabela15 = tabela15.loc[(tabela15['TP_SEXO'].notnull())]
tabela15 = tabela15.loc[(tabela15['QE_I08'].notnull())]
tabela15 = tabela15.loc[(tabela15['QE_I02'].notnull())]
# tabela15 = tabela15.loc[(tabela15['CO_TURNO_GRADUACAO'].notnull())]

'''
93 = Pessoa Jurídica de Direito Público - Federal 
115 = Pessoa Jurídica de Direito Público - Estadual
116 = Pessoa Jurídica de Direito Público - Municipal
118 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Civil
121 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Fundação
10001 = Pessoa Jurídica de Direito Público - Estadual
10002 = Pessoa Jurídica de Direito Público - Federal
10003 = Pessoa Jurídica de Direito Público - Municipal
10005 = Privada com fins lucrativos
10006 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Mercantil ou Comercial
10007 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Associação de Utilidade Pública
10008 = Privada sem fins lucrativos
10009 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Sociedade
'''

##Mapeamento CO_CATEGAD
# 0 = publica, 1 = privada
tabela15['CO_CATEGAD'] = tabela15['CO_CATEGAD'].map({'93': 0, '115': 0, '116': 0, '118' : 1, '121' : 1, '10002': 0,
                                                     '10001' : 0, '10003' : 0, '10005' : 1, '10006' : 1, 
                                                    '10007' : 1, '10008' : 1, '10009' : 1})

#Mapeamento tipo sexo
tabela15['TP_SEXO'] = tabela15['TP_SEXO'].map({'M': 0, 'F': 1, 'N' : 3})
#tabela.head(10)

# ##Mapeamento RENDA
tabela15['QE_I08'] = tabela15['QE_I08'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6, 'G' : 7})

'''
Como você se considera?	
A = Branco(a).
B = Negro(a).
C = Pardo(a)/mulato(a).
D = Amarelo(a) (de origem oriental).
E = Indígena ou de origem indígena.
'''

# ##Mapeamento COR
tabela15['QE_I02'] = tabela15['QE_I02'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5})

##Mapeamento questão 17
tabela15['QE_I17'] = tabela15['QE_I17'].map({'A': 1, 'B': 2, 'C': 3, 'D': 1,'E': 2, 'F':3})

tabela.append(tabela15)

In [19]:
#TODAS
tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/cor
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'NU_IDADE', 'TP_SEXO', 'QE_I08'])

#s/RENDA
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I02'])

#s/SEXO
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'QE_I08', 'QE_I02'])

#s/IDADE
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/Q17
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/regiao
# tabela14 = pandas.DataFrame(enade[3], columns = ['CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

##Ignora valores nulos
tabela14 = tabela14.loc[(tabela14['CO_REGIAO_CURSO'].notnull())]
tabela14 = tabela14.loc[(tabela14['CO_CATEGAD'].notnull())]
tabela14 = tabela14.loc[(tabela14['QE_I17'].notnull())]
tabela14 = tabela14.loc[(tabela14['NU_IDADE'].notnull())]
tabela14 = tabela14.loc[(tabela14['TP_SEXO'].notnull())]
tabela14 = tabela14.loc[(tabela14['QE_I08'].notnull())]
tabela14 = tabela14.loc[(tabela14['QE_I02'].notnull())]
# tabela14 = tabela14.loc[(tabela14['CO_TURNO_GRADUACAO'].notnull())]

'''
93 = Pessoa Jurídica de Direito Público - Federal
116 = Pessoa Jurídica de Direito Público - Municipal
118 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Civil
121 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Fundação
10001 = Pessoa Jurídica de Direito Público - Estadual
10002 = Pessoa Jurídica de Direito Público - Federal
10003 = Pessoa Jurídica de Direito Público - Municipal
10004 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Associação de Utilidade Pública
10005 = Privada com fins lucrativos
10006 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Mercantil ou Comercial
10007 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Associação de Utilidade Pública
10008 = Privada sem fins lucrativos
10009 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Sociedade
'''

##Mapeamento CO_CATEGAD
tabela14['CO_CATEGAD'] = tabela14['CO_CATEGAD'].map({'93': 0, '116': 0, '118' : 1, '121' : 1, '10002': 0,
                                                     '10001' : 0, '10003' : 0, '10005' : 1, '10004' : 1, '10006' : 1, 
                                                    '10007' : 1, '10008' : 1, '10009' : 1})


#Mapeamento tipo sexo
tabela14['TP_SEXO'] = tabela14['TP_SEXO'].map({'M': 0, 'F': 1, 'N' : 3})
#tabela.head(10)

# ##Mapeamento RENDA
tabela14['QE_I08'] = tabela14['QE_I08'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6, 'G' : 7})

'''
Como você se considera?	
A = Branco(a).
B = Negro(a).
C = Pardo(a)/mulato(a).
D = Amarelo(a) (de origem oriental).
E = Indígena ou de origem indígena.
'''

# ##Mapeamento COR
tabela14['QE_I02'] = tabela14['QE_I02'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5})

##Mapeamento questão 17
tabela14['QE_I17'] = tabela14['QE_I17'].map({'A': 1, 'B': 2, 'C': 3, 'D': 1,'E': 2, 'F':3})

tabela.append(tabela14)
#tabela[3].head(10)


In [21]:
#TODAS
tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I16','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/cor
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'NU_IDADE', 'TP_SEXO', 'QE_I08'])

#s/RENDA
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I02'])

#s/SEXO
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17','NU_IDADE', 'QE_I08', 'QE_I02'])

#s/IDADE
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'QE_I17', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/Q17
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_REGIAO_CURSO', 'CO_CATEGAD', 'NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

#s/regiao
# tabela13 = pandas.DataFrame(enade[4], columns = ['CO_CATEGAD', 'QE_I17','NU_IDADE', 'TP_SEXO', 'QE_I08', 'QE_I02'])

##Ignora valores nulos
tabela13 = tabela13.loc[(tabela13['CO_REGIAO_CURSO'].notnull())]
tabela13 = tabela13.loc[(tabela13['CO_CATEGAD'].notnull())]
tabela13 = tabela13.loc[(tabela13['QE_I16'].notnull())]
tabela13 = tabela13.loc[(tabela13['NU_IDADE'].notnull())]
tabela13 = tabela13.loc[(tabela13['TP_SEXO'].notnull())]
tabela13 = tabela13.loc[(tabela13['QE_I08'].notnull())]
tabela13 = tabela13.loc[(tabela13['QE_I02'].notnull())]
# tabela13 = tabela13.loc[(tabela13['CO_TURNO_GRADUACAO'].notnull())]

##Mapeamento questão 16
tabela13['QE_I16'] = tabela13['QE_I16'].map({'A': 1, 'B': 2, 'C': 1, 'D': 2})
#tabela.head(10)

'''
93 = Pessoa Jurídica de Direito Público - Federal
116 = Pessoa Jurídica de Direito Público - Municipal
118 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Civil
121 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Fundação
10001 = Pessoa Jurídica de Direito Público - Estadual
10002 = Pessoa Jurídica de Direito Público - Federal
10003 = Pessoa Jurídica de Direito Público - Municipal
10005 = Privada com fins lucrativos
10006 = Pessoa Jurídica de Direito Privado - Com fins lucrativos - Sociedade Mercantil ou Comercial
10007 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Associação de Utilidade Pública
10008 = Privada sem fins lucrativos
10009 = Pessoa Jurídica de Direito Privado - Sem fins lucrativos - Sociedade
'''

##Mapeamento CO_CATEGAD
tabela13['CO_CATEGAD'] = tabela13['CO_CATEGAD'].map({'93': 0, '116': 0, '118' : 1, '121' : 1, '10002': 0,
                                                     '10001' : 0, '10003' : 0, '10005' : 1, '10006' : 1, 
                                                    '10007' : 1, '10008' : 1, '10009' : 1})

#Mapeamento tipo sexo
tabela13['TP_SEXO'] = tabela13['TP_SEXO'].map({'M': 0, 'F': 1, 'N' : 3})
#tabela.head(10)

# ##Mapeamento RENDA
tabela13['QE_I08'] = tabela13['QE_I08'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5, 'F' : 6})

'''
Como você se considera?	
A = Branco(a).
B = Negro(a).
C = Pardo(a)/mulato(a).
D = Amarelo(a) (de origem oriental).
E = Indígena ou de origem indígena.
'''

# ##Mapeamento COR
tabela13['QE_I02'] = tabela13['QE_I02'].map({'A': 1, 'B': 2, 'C': 3, 'D' : 4, 'E' : 5})

tabela.append(tabela13)

In [22]:
# Classificador KNN 2017
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection  import  train_test_split 

#Algoritmo knn passando o valor de k=150
knn = KNeighborsClassifier(n_neighbors = 50)

# TESTES 01
X = tabela17
X = X.drop(['CO_CATEGAD'], axis = 1)
y = tabela17['CO_CATEGAD'] # target


# dados de treinamento 'até 40%' da base
X_train ,  X_test ,  y_train ,  y_teste  =  train_test_split (X ,  y ,  test_size = 0.7 ,  random_state = 42) 

knn.fit(X_train,y_train)

# validacão com o restante dos dados
y_pred = knn.predict(X_test)

#resultado encontrado
# print(y_pred)
#resultado esperado
# print(y_teste)   

#Precisão da predição
precisao = knn.score(X_test, y_teste) #Teste em porcentagem.

print('Precisão obtida: ', precisao)

Precisão obtida:  0.6932948435972629


In [23]:
# Random Forest Classification 2017

RFCX = tabela17
RFCX = RFCX.drop(['CO_CATEGAD'], axis = 1)
RFCy = tabela17['CO_CATEGAD'] # target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
RFCX_train, RFCX_test, RFCy_train, RFCy_test = train_test_split(RFCX, RFCy, test_size = 0.7, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
RFCX_train = sc.fit_transform(RFCX_train)
RFCX_test = sc.transform(RFCX_test)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
#tenta vários números de arvores p ver o melhor resultado
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0) 
classifier.fit(RFCX_train, RFCy_train)

# Predicting the Test set results
RFCy_pred = classifier.predict(RFCX_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(RFCy_test, RFCy_pred)

print("\n CONFUSION MATRIX: \n", cm)

#Precisão da predição
precisao = classifier.score(RFCX_test, RFCy_test) #Teste em porcentagem.

print('Precisão obtida: ', precisao)


 CONFUSION MATRIX: 
 [[ 52354  64322     10]
 [ 37549 171821     10]
 [   866    427      1]]
Precisão obtida:  0.6847996089931574


In [24]:
# Classificador KNN 2016

#Algoritmo knn passando o valor de k=150
knn16 = KNeighborsClassifier(n_neighbors = 50)

# TESTES 01
X16 = tabela16
X16 = X16.drop(['CO_CATEGAD'], axis = 1)
y16 = tabela16['CO_CATEGAD'] # target


# dados de treinamento 'até 40%' da base
X_train16 ,  X_test16 ,  y_train16 ,  y_teste16  =  train_test_split (X16 ,  y16 ,  test_size = 0.7 ,  random_state = 42) 

knn16.fit(X_train16,y_train16)

# validacão com o restante dos dados
y_pred16 = knn16.predict(X_test16)

#resultado encontrado
# print(y_pred)
#resultado esperado
# print(y_teste)   

#Precisão da predição
precisao16 = knn16.score(X_test16, y_teste16) #Teste em porcentagem.

print('Precisão obtida: ', precisao16)

Precisão obtida:  0.7669581159215908


In [25]:
# Random Forest Classification 2016

RFCX16 = tabela16
RFCX16 = RFCX16.drop(['CO_CATEGAD'], axis = 1)
RFCy16 = tabela16['CO_CATEGAD'] # target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
RFCX_train16, RFCX_test16, RFCy_train16, RFCy_test16 = train_test_split(RFCX16, RFCy16, test_size = 0.7, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
RFCX_train16 = sc.fit_transform(RFCX_train16)
RFCX_test16 = sc.transform(RFCX_test16)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
#tenta vários números de arvores p ver o melhor resultado
classifier16 = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0) 
classifier16.fit(RFCX_train16, RFCy_train16)

# Predicting the Test set results
RFCy_pred16 = classifier16.predict(RFCX_test16)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm16 = confusion_matrix(RFCy_test16, RFCy_pred16)

print("\n CONFUSION MATRIX: \n", cm16)

#Precisão da predição
precisao16 = classifier16.score(RFCX_test16, RFCy_test16) #Teste em porcentagem.

print('Precisão obtida: ', precisao16)


 CONFUSION MATRIX: 
 [[  4234  28714]
 [  6652 102220]]
Precisão obtida:  0.7506275560569736


In [26]:
# Classificador KNN 2015

#Algoritmo knn passando o valor de k=150
knn15 = KNeighborsClassifier(n_neighbors = 50)

# TESTES 01
X15 = tabela15
X15 = X15.drop(['CO_CATEGAD'], axis = 1)
y15 = tabela15['CO_CATEGAD'] # target


# dados de treinamento 'até 40%' da base
X_train15 ,  X_test15 ,  y_train15 ,  y_teste15  =  train_test_split (X15 ,  y15 ,  test_size = 0.7 ,  random_state = 42) 

knn15.fit(X_train15,y_train15)

# validacão com o restante dos dados
y_pred15 = knn15.predict(X_test15)

#resultado encontrado
# print(y_pred)
#resultado esperado
# print(y_teste)   

#Precisão da predição
precisao15 = knn15.score(X_test15, y_teste15) #Teste em porcentagem.

print('Precisão obtida: ', precisao15)

Precisão obtida:  0.8600320469859992


In [27]:
# Random Forest Classification 2015

RFCX15 = tabela15
RFCX15 = RFCX15.drop(['CO_CATEGAD'], axis = 1)
RFCy15 = tabela15['CO_CATEGAD'] # target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
RFCX_train15, RFCX_test15, RFCy_train15, RFCy_test15 = train_test_split(RFCX15, RFCy15, test_size = 0.7, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
RFCX_train15 = sc.fit_transform(RFCX_train15)
RFCX_test15 = sc.transform(RFCX_test15)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
#tenta vários números de arvores p ver o melhor resultado
classifier15 = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0) 
classifier15.fit(RFCX_train15, RFCy_train15)

# Predicting the Test set results
RFCy_pred15 = classifier15.predict(RFCX_test15)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm15 = confusion_matrix(RFCy_test15, RFCy_pred15)

print("\n CONFUSION MATRIX: \n", cm15)

#Precisão da predição
precisao15 = classifier15.score(RFCX_test15, RFCy_test15) #Teste em porcentagem.

print('Precisão obtida: ', precisao15)


 CONFUSION MATRIX: 
 [[  1081  44863]
 [  3671 278653]]
Precisão obtida:  0.8521512910183143


In [28]:
# Classificador KNN 2014

#Algoritmo knn passando o valor de k=150
knn14 = KNeighborsClassifier(n_neighbors = 50)

# TESTES 01
X14 = tabela14
X14 = X14.drop(['CO_CATEGAD'], axis = 1)
y14 = tabela14['CO_CATEGAD'] # target


# dados de treinamento 'até 40%' da base
X_train14 ,  X_test14 ,  y_train14 ,  y_teste14  =  train_test_split (X14 ,  y14 ,  test_size = 0.7 ,  random_state = 42) 

knn14.fit(X_train14,y_train14)

# validacão com o restante dos dados
y_pred14 = knn14.predict(X_test14)

#resultado encontrado
# print(y_pred)
#resultado esperado
# print(y_teste)   

#Precisão da predição
precisao14 = knn14.score(X_test14, y_teste14) #Teste em porcentagem.

print('Precisão obtida: ', precisao14)

Precisão obtida:  0.7153943942096738


In [29]:
# Random Forest Classification 2014

RFCX14 = tabela14
RFCX14 = RFCX14.drop(['CO_CATEGAD'], axis = 1)
RFCy14 = tabela14['CO_CATEGAD'] # target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
RFCX_train14, RFCX_test14, RFCy_train14, RFCy_test14 = train_test_split(RFCX14, RFCy14, test_size = 0.7, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
RFCX_train14 = sc.fit_transform(RFCX_train14)
RFCX_test14 = sc.transform(RFCX_test14)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
#tenta vários números de arvores p ver o melhor resultado
classifier14 = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0) 
classifier14.fit(RFCX_train14, RFCy_train14)

# Predicting the Test set results
RFCy_pred14 = classifier14.predict(RFCX_test14)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm14 = confusion_matrix(RFCy_test14, RFCy_pred14)

print("\n CONFUSION MATRIX: \n", cm14)

#Precisão da predição
precisao14 = classifier14.score(RFCX_test14, RFCy_test14) #Teste em porcentagem.

print('Precisão obtida: ', precisao14)


 CONFUSION MATRIX: 
 [[ 60570  52786]
 [ 32912 146358]]
Precisão obtida:  0.7071415390293412


In [30]:
# Classificador KNN 2013

#Algoritmo knn passando o valor de k=150
knn13 = KNeighborsClassifier(n_neighbors = 50)

# TESTES 01
X13 = tabela13
X13 = X13.drop(['CO_CATEGAD'], axis = 1)
y13 = tabela13['CO_CATEGAD'] # target


# dados de treinamento 'até 40%' da base
X_train13 ,  X_test13 ,  y_train13 ,  y_teste13  =  train_test_split (X13 ,  y13 ,  test_size = 0.7 ,  random_state = 42) 

knn13.fit(X_train13, y_train13)

# validacão com o restante dos dados
y_pred13 = knn13.predict(X_test13)

#resultado encontrado
# print(y_pred)
#resultado esperado
# print(y_teste)   

#Precisão da predição
precisao13 = knn13.score(X_test13, y_teste13) #Teste em porcentagem.

print('Precisão obtida: ', precisao13)

Precisão obtida:  0.7566915991840267


In [31]:
# Random Forest Classification 2013

RFCX13 = tabela13
RFCX13 = RFCX13.drop(['CO_CATEGAD'], axis = 1)
RFCy13 = tabela13['CO_CATEGAD'] # target

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
RFCX_train13, RFCX_test13, RFCy_train13, RFCy_test13 = train_test_split(RFCX13, RFCy13, test_size = 0.7, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
RFCX_train13 = sc.fit_transform(RFCX_train13)
RFCX_test13 = sc.transform(RFCX_test13)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
#tenta vários números de arvores p ver o melhor resultado
classifier13 = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0) 
classifier13.fit(RFCX_train13, RFCy_train13)

# Predicting the Test set results
RFCy_pred13 = classifier13.predict(RFCX_test13)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm13 = confusion_matrix(RFCy_test13, RFCy_pred13)

print("\n CONFUSION MATRIX: \n", cm13)

#Precisão da predição
precisao13 = classifier13.score(RFCX_test13, RFCy_test13) #Teste em porcentagem.

print('Precisão obtida: ', precisao13)


 CONFUSION MATRIX: 
 [[ 3615 23559]
 [ 5127 80938]]
Precisão obtida:  0.7466773814675156
